"""Reusable preview table for generated data."""

from __future__ import annotations

from PyQt6.QtWidgets import QHeaderView, QTableWidget, QTableWidgetItem


class PreviewTableWidget(QTableWidget):
    """Display preview rows generated from mapped report output."""

    def load_rows(self, rows: list[dict[str, object]]) -> None:
        """Render preview rows from dictionaries.

        Args:
            rows: Preview rows generated by the preview service.
        """

        headers = list(rows[0].keys()) if rows else []
        self.clear()
        self.setColumnCount(len(headers))
        self.setRowCount(len(rows))
        self.setHorizontalHeaderLabels(headers)
        self.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)

        for row_index, row in enumerate(rows):
            for column_index, header in enumerate(headers):
                value = "" if row[header] is None else str(row[header])
                self.setItem(row_index, column_index, QTableWidgetItem(value))
